const path = require('path');
const _root = path.resolve(__dirname, '..');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const WorkboxPlugin = require('workbox-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const webpack = require("webpack");

/**
 * Fetch app root
 * @param args
 * @returns {string}
 */
function root(args) {
    args = Array.prototype.slice.call(arguments, 0);
    let target_dir = path.join.apply(path, [_root].concat(args));
    console.log("Watching content from:", target_dir);
    return target_dir;
}

module.exports = {
    mode: 'development',
    resolve: {
        extensions: ['.js', '.ts', '.html']
    },
    entry: {
        polyfills: "./src/app/index.polyfill.ts",
        main: "./src/app/index.ts",
        styles: "./src/app/assets/css/app-styles.scss"
    },
    output: {
        path: path.resolve(__dirname, 'output'), // output directory
        filename: "[hash].[name].js" // name of the generated bundle
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                loader: ["style-loader", "css-loader"]
            },
            {
                test: /\.html$/,
                exclude: /node_modules/,
                use: {loader: 'html-loader'}
            },
            {
                test: /\.ts$/,
                loader: "ts-loader"
            },
            {
                test: /\.ts$/,
                enforce: "pre",
                loader: 'tslint-loader'
            },
            {
                test: /\.scss$/,
                loader: ["style-loader", "css-loader?sourceMap", "sass-loader?sourceMap"]
            }
        ]
    },
    plugins: [
        new CleanWebpackPlugin([ 'output' ], {
            root: __dirname,
            verbose: true,
            dry: false
        }),
        new HtmlWebpackPlugin({
            template: "./src/app/index.html",
        }),
        new webpack.ContextReplacementPlugin(
            /\@angular(\\|\/)core(\\|\/)esm5/,
            root('iex-commander/src'),
            {
                // Angular Async Routes
            }
        ),
        new CopyWebpackPlugin([
            { from: require.resolve('workbox-sw'), to: 'workbox-sw.prod.js'}
        ]),
        new WorkboxPlugin.InjectManifest({
            // Source to manifest
            swSrc: './src/app/workers/ServiceWorkerManifest.js',
            // Output file generated by webpack
            swDest: 'service-worker.js',
            importWorkboxFrom: 'disabled'
        })
    ],
    devtool: "source-map",
    devServer: {
        https: false,
        overlay: true,
        historyApiFallback: true,
        stats: {
            warningsFilter: /System\.import/
        }
    }
};